# Generated by Django 3.0 on 2020-03-27 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='displaypic',
        ),
    ]
